name: Commit Check

on:
  push:
  pull_request:
    branches: [main, development]

jobs:
  commit-check:
    uses: Diaszano/actions/.github/workflows/commit-check.yaml@v1.0.0
    with:
      pr-comments: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
